#baseURL = "localhost:1313/exception"
baseURL = "https://github.com/miyamam/miyamam.github.io"
languageCode = "ja"
#defaultContentLanguage = "en"

##################
# Kraiklyn
##################
theme = "Kraiklyn"
themesdir = "./themes"

name = "Kraiklyn"
license = "MIT"
licenselink = "https://github.com/jsnjack/kraiklyn/blob/master/LICENSE.md"
description = "A theme for a simple one page documentation"
homepage = "https://github.com/jsnjack/kraiklyn/"
tags = ["one page", "docs", "documentation", "simple", "minimalistic"]
features = []
min_version = "0.33"

# Adding menu entries to the external links section
[params]
externalTitle = "Surfly docs"

[[menu.shortcuts]]
name = "Javascript API"
url = "https://docs.surfly.com/javascript.html"
weight = 20

[author]
  name = "Yauhen Shulitski"
  homepage = "https://github.com/jsnjack"


# ####################
# ## hugo-theme-learn
# ####################
# title = "Hugo Learn Documentation"
# theme = "hugo-theme-learn"
# themesdir = "./themes"
# metaDataFormat = "yaml"
# defaultContentLanguageInSubdir= true

# [params]
# # https://github.com/miyamam/miyamam.github.io/
#   editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
#   description = "Documentation for Hugo Learn Theme"
#   author = "Mathieu Cornic"
#   showVisitedLinks = true

# [outputs]
# home = [ "HTML", "RSS", "JSON"]

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo Learn Theme"
# weight = 1
# languageName = "English"

# [[Languages.en.menu.shortcuts]] 
# name = "<i class='fa fa-fw fa-github'></i> Github repo"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-camera'></i> Showcases"
# url = "showcase"
# weight = 11

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30

# [Languages.fr]
# title = "Documentation du thème Hugo Learn"
# weight = 2
# languageName = "Français"

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-github'></i> Repo Github"
# identifier = "ds"
# url = "https://github.com/miyamam"
# weight = 10

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-camera'></i> Vitrine"
# url = "/showcase"
# weight = 11

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-bookmark'></i> Documentation Hugo"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-fw fa-bullhorn'></i> Crédits"
# url = "/credits"
# weight = 30
